### ISSUE TITLE
b_C_Base position does not apply correctly with start frame in BAC

### ISSUE THREAD

**Issue by HalloweenPandas** [LazyBone152/XenoKit#3] opened 2023-05-12 19:32 UTC
When the Animation entry in the BAC has a start frame value other than 0 and that animation has location keyframes on the b_C_Base, the position of the b_C_Base bone does not get set correctly.

For an example check Saiyan Spirit BAC Entry 3, the first animation entry in there has a start time of 116. If you put the start time on 0 the position does get applied correctly.

### Position with start time on 116
![image](https://github.com/LazyBone152/XenoKit/assets/51948142/7e4879bf-451b-4f84-a44e-e335ae2c1256)

### Position with start time on 0
![image](https://github.com/LazyBone152/XenoKit/assets/51948142/f667b554-a2bf-4a34-84f1-773dc2e63f94)

This also affects the camera, since I assume the b_C_Base bone is handled differently than the g_x_LND and g_x_CAM bone. Which could also be an issue since they should follow the location, rotation and scale of b_C_Base and then if those bones (LND or CAM) have any location data it applies to location ontop of where the b_C_Base bone is currently located. Could explain this in more detail if neccessary.

Another issue I found while writing this issue is that when you have a start time and you use the next frame and previous frame buttons, the animation preview shows the incorrect frame of the animation.

**Comment by LazyBone152** [comment] 2023-05-12 22:04
This is actually intended and how it works in the game too.

Any movement on b_C_Base moves the characters world position (if the BAC flags are set), and any movement in the animation before the start frame is ignored. The “Full Root Motion” flag does make b_C_Base be treated as a regular bone and shows the full movement, but will wont actually move the character (will revert to original position at end of animation).

Since the character is moved with b_C_Base, then when entry 3 starts in this skill you would already be in the correct place since the other entries would have moved you already. But in XenoKit the position is always reset when ending a BAC entry, so you don't see this there.

**Comment by LazyBone152** [comment] 2023-05-12 22:10
Confirmed the issue with prev/next frame. Not sure why this particular feature gives me so much trouble...

**Comment by LazyBone152** [comment] 2023-05-13 13:06
prev/next frame bug has been fixed in 0.1.1.

I'll have to look into what g_x_LND is doing with this skill later since it definitely seems broken here. It should be following the character (b_C_Base) as you say but clearly isn't.

**Closed** 2023-05-15 20:57 UTC
